@startuml
'https://plantuml.com/class-diagram

class TestRailXXX extends TestRailData {
    @Entity
    @Getter & Setter
    @Table tr_xxx
}

class TestRailXXXFactory {
    @Component

    + create(String name): TestRailXXX
    + create(JSONObject xxxJson) : TestRailXXX
}

interface TestRailxxxRepository extends JpaRepository<TestRailXXX, Long> {
    @Repository
    Optional<TestRailxxx> findByTRId(Integer id);

    Optional<TestRailxxx> findByName(String name);
    ...
}

class TestRailxxxService {
    @Service

    - TestRailxxxRepository testRailxxxRepository
    - TestRailxxxFactory testRailxxxFactory

    + create(String name): TestRailXXX
    + create(JSONObject xxxJson) : TestRailXXX
    + save(TestRailXXX xxx): TestRailXXX
    + findById(Long id): Optional<TestRailXXX>
    + findByTRId(Integer id): Optional<TestRailXXX>
    + findByName(String name): Optional<TestRailXXX>
    ...
}

class xxxSavingManager {
    @Service

        - TestRailxxxService testRailxxxService
        - xxxQueryTestRail xxxQueryTestRail

        + save(TestRailXXX xxx): DataResponseFromTR
        + delete(TestRailXXX xxx): DataResponseFromTR
        ...
}

class xxxQueryTestRail {
    @Static class
    - HttpSenderToTR httpSenderToTR

    + add(String (String name) : DataResponseFromTR

    + delete(String name) : DataResponseFromTR
}

class GeneralSavingManager {
    @Service

    - xxxSavingManager xxxSavingManager

    + saveXXX(TestRailXXX xxx): void
    + deleteXXX(TestRailXXX xxx): void
}

@enduml