@startuml
'https://plantuml.com/class-diagram


class GatlingTestCase {
        @Entity
        @Getter & Setter
        @Table tr_gatling_test_case

        - id: Long
        - sectionId: int
        - title: String
        - templateId: int
        - typeId: int
        - priorityId: int
        - estimate: TimeStamp
        - milestoneId: int
        - refs: String

}
class GatlingResult {
    @Entity
    @Getter & Setter
    @Table tr_gatling_result

    - id: Long
    - statusId: int
    - comment: String
    - version: String
    - elapsed: String
    - defects: String
    - assignedToId: int
    - date: TimeStamp
}

@enduml