@startuml
'https://plantuml.com/sequence-diagram



actor User
entity TRData
participant TRDataFactory #yellowgreen
participant DataInterface #red
participant ErrorHandler #red
participant DataSavingService #orange
participant TAFDataSavingService #orange
participant TRDataSavingService #orange
participant DataSender #lightblue
database DataStorage
collections TestRailAPI


== Creating From TAF to TestRail ==
User -> DataInterface : new(...)

activate DataInterface

group Create TRData
    DataInterface -> TRDataFactory : new(...)

    activate TRDataFactory

    TRDataFactory -> TRData : new(...)

    activate TRData

    TRData --> TRDataFactory : TRData

    deactivate TRData

    TRDataFactory --> DataInterface : TRData

    deactivate TRDataFactory
end



DataInterface -> DataSavingService : saveData(TRData)

activate DataSavingService

DataSavingService -> DataSavingService : setDataUnSaved(Data)

DataSavingService -> TRDataSavingService : saveData(TRData)

activate TRDataSavingService

TRDataSavingService -> DataSender : send(TRData)

activate DataSender

DataSender -> TestRailAPI : send(TRData)

activate TestRailAPI
alt Success
    TestRailAPI --> DataSender : success http code 200 + response
    DataSender --> TRDataSavingService : success code 0 + response
    TRDataSavingService -> TRDataSavingService : Update TRData with response
    TRDataSavingService -> TRDataSavingService : setTRSaved(TRData)
    TRDataSavingService --> DataSavingService : success code 0 + TRData


    group Save Locally

        DataSavingService -> TAFDataSavingService : saveData(Data)

        activate TAFDataSavingService

        TAFDataSavingService -> DataStorage : send(Data)

        activate DataStorage

        DataStorage -> DataStorage : save(Data)

        DataStorage --> TAFDataSavingService : Data

        deactivate DataStorage

        TAFDataSavingService --> DataSavingService : Data

        deactivate TAFDataSavingService
    end

    DataSavingService -> DataSavingService : setSaved(Data)


else Error

    TestRailAPI --> DataSender : error + response
    deactivate TestRailAPI

    DataSender --> TRDataSavingService : error + response

    deactivate DataSender

    TRDataSavingService -> ErrorHandler : sendTRConnexionError(error, response)

    TRDataSavingService --> DataSavingService : error + TRData

    deactivate

    note over DataSavingService : Save Locally
    DataSavingService -> DataSavingService : setLocallySaved(Data)
end

DataSavingService --> DataInterface : code  + TRData

@enduml