@startuml
'https://plantuml.com/class-diagram

interface ExportServiceInterface {
    + exportData()
}

class ExportService implements ExportServiceInterface{
    + exportData()
}

ExportService *-up- XCollector
ExportService *-up- JmeterCollector
ExportService *-up- SeleniumCollector
ExportService *-up- GatlingCollector

class ExportA implements ExportServiceInterface {
    + exportData()
}

ExportA -up-* ExportService

class ExportB implements ExportServiceInterface {
    + exportData()
}
ExportB -up-* ExportService

interface CollectData {
    + collectData()
}

class JmeterCollector implements CollectData {
    + collectData()
}

class SeleniumCollector implements CollectData {
    + collectData()
}

class GatlingCollector implements CollectData {
    + collectData()
}

class XCollector implements CollectData {
    + collectData()
}

interface ParseData {
    + parseData()
}


class JmeterParser implements ParseData {
    + parseData()
}

JmeterParser --* JmeterCollector

class SeleniumParser implements ParseData {
    + parseData()
}

SeleniumParser --* SeleniumCollector

class GatlingParser implements ParseData {
    + parseData()
}

GatlingParser --* GatlingCollector

class XParser implements ParseData {
    + parseData()
}

XParser --* XCollector





@enduml